# Generated by Django 4.1.7 on 2023-02-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='New.user'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='New.user'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
