# Generated by Django 4.1.7 on 2023-02-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0002_remove_user_id_task_userid_alter_role_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='userid',
            new_name='name',
        ),
    ]
