# Generated by Django 4.1.7 on 2023-02-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0004_rename_name_task_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='userid',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='New.user'),
            preserve_default=False,
        ),
    ]
