# Generated by Django 4.1.7 on 2023-02-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0006_remove_task_name_alter_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AddField(
            model_name='role',
            name='roleid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
