# Generated by Django 4.1.7 on 2023-02-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0007_remove_role_id_role_roleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='roleid',
            field=models.IntegerField(),
        ),
    ]
